version: "2"

before:
  hooks:
    - go mod tidy

builds:
  - binary: griddo-env
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -extldflags '-static' -X 'main.version={{.Version}}' -X 'main.commit={{ .ShortCommit }}'

release:
  prerelease: auto

universal_binaries:
  - name_template: 'server-cx'
    replace: true

brews:
  - name: server-cx
    homepage: https://github.com/danielrosse/InstanceServerCX
    description: "Launch a local server for CX"
    repository:
      owner: danielrosse
      name: homebrew-env
    commit_author:
      name: server-cx
      email: daniel.rossello@secuoyas.com

checksum:
  name_template: 'checksums.txt'
